[en]
  title = "Dang T. Hung's webpage"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[vi]
  title = "Trang web của Hưng"
  languageName = "Tiếng Việt"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/vi"
