[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "event"
  name = "Events"
  url = "event"
  weight = 3



#[[main]]
#  identifier = "posts"
#  name = "Posts"
#  url = "posts"
#  weight = 4


#[[main]]
#  parent = "posts"
#  name = "News"
#  url = "posts/news"

[[main]]
  identifier = "misc"
  name = "Misc"
  url = "misc"
  weight = 4

[[main]]
  identifier = "research"
  name = "Research"
  url = "research"
  weight = 2

