[[main]]
  identifier = "about"
  name = "Về tôi"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Lưu trữ"
  url = "archive"
  weight = 4

[[main]]
  identifier = "gallery"
  name = "Bộ sưu tập"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "Ảnh"
  url = "gallery/photo"


[[main]]
  identifier = "posts"
  name = "Bài viết"
  url = "posts"
  weight = 2